DROP TABLE FAQ;
CREATE TABLE FAQ
(
    FAQ_NO NUMBER NOT NULL,
    FAQ_TITLE VARCHAR2(100 BYTE),
    FAQ_CONTENT VARCHAR2(500 BYTE),
    FAQ_CREATED DATE NOT NULL
);

ALTER TABLE FAQ
    ADD CONSTRAINT FAQ_PK
        PRIMARY KEY(FAQ_NO);
        
DROP SEQUENCE FAQ_SEQ;
CREATE SEQUENCE FAQ_SEQ NOCACHE;

    