-- 테이블 초기화
DROP TABLE MEMBER_LOG;
DROP TABLE SIGN_OUT_MEMBER;
DROP TABLE MEMBER;
DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE PAYMENT;

-- 관리자(나중에 1번으로 insert하기)/ 탈퇴막기

CREATE TABLE MEMBER_LOG (
    MEMBER_LOG_NO	NUMBER	NOT NULL,        -- PK
	MEMBER_ID	    VARCHAR2(30 BYTE)	NOT NULL UNIQUE,	-- FK
	SIGN_UP     	DATE	NOT NULL   -- 로그인 일시
);

CREATE TABLE SIGN_OUT_MEMBER (
	SIGN_OUT_NO	NUMBER	NOT NULL,           -- PK
	MEMBER_NO	NUMBER	NOT NULL,           
	ID	        VARCHAR2(50 BYTE) NOT NULL UNIQUE,
	NAME	    VARCHAR2(50 BYTE),
	EMAIL	    VARCHAR2(50 BYTE),
    AGREE_STATE	NUMBER,              	    -- 동의여부
    SIGN_IN	    DATE	NOT NULL,     		-- 가입일
	SIGN_OUT	DATE    DEFAULT SYSDATE     -- 탈퇴일
);


CREATE TABLE MEMBER (
	MEMBER_NO	        NUMBER	NOT NULL,               -- PK
	MEMBER_NAME 	    VARCHAR2(50 BYTE)	NOT NULL,
	MEMBER_EMAIL	    VARCHAR2(50 BYTE)	NOT NULL UNIQUE,
	MEMBER_ID	        VARCHAR2(50 BYTE)	NOT NULL UNIQUE,
	MEMBER_PW	        VARCHAR2(80 BYTE)	NOT NULL,
	MEMBER_PHONE	    VARCHAR2(30 BYTE),
	MEMBER_BIRTH	    NUMBER,
	AGREE_STATE	        NUMBER,
	SIGN_IN	    		DATE	NOT NULL,	-- 가입일
	MEMBER_SESSIONID    VARCHAR2(50 BYTE),  -- 세션ID
    RESER_NO	NUMBER	NOT NULL,
    PAY_NO	    NUMBER	NOT NULL,
    ROOM_NO 	    NUMBER	NOT NULL
);

CREATE TABLE RESERVATION (
	RESER_NO	NUMBER	NOT NULL, 			 -- PK
	MEMBER_NO	NUMBER	NOT NULL,
	ROOM_NO	NUMBER	NOT NULL,
	RT_NO	NUMBER	NOT NULL,
	NON_NO	NUMBER	NOT NULL,
    RESER_CHECKIN	DATE,
	RESER_CHECKOUT	DATE,
	RESER_STATUS	NUMBER,
    RESER_CNT	NUMBER
);

CREATE TABLE PAYMENT (
	PAY_NO	    NUMBER	NOT NULL,			-- PK
	RESER_NO	NUMBER	NOT NULL,
	PAY_RT_NO	NUMBER	NOT NULL,
	PAY_DATE	DATE	NULL,
	PAY_WAY	    VARCHAR2(10 BYTE)	NOT NULL
);


CREATE TABLE ROOM (
	ROOM_NO 	    NUMBER	NOT NULL,		-- PK
	RT_NO	        NUMBER	NOT NULL,
	ROOM_NAME	    VARCHAR2(30 BYTE)	NOT NULL,
	ROOM_STATUS 	NUMBER	NOT NULL,
	ROOM_CHECKIN	DATE	NULL,
	ROOM_CHECKOUT	DATE	NULL,
	ROOM_PRICE	    NUMBER	NOT NULL
);



-- 시퀀스
DROP SEQUENCE MEMBER_LOG_SEQ;
DROP SEQUENCE SIGN_OUT_MEMBER_SEQ;
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE PAYMENT_SEQ;
DROP SEQUENCE ROOM_SEQ;

CREATE SEQUENCE MEMBER_LOG_SEQ NOCACHE;
CREATE SEQUENCE SIGN_OUT_MEMBER_SEQ NOCACHE;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;
CREATE SEQUENCE RESERVATION_SEQ NOCACHE;
CREATE SEQUENCE PAYMENT_SEQ NOCACHE;
CREATE SEQUENCE ROOM_SEQ NOCACHE;



-- 기본키
ALTER TABLE MEMBER_LOG ADD CONSTRAINT MEMBER_LOG_PK PRIMARY KEY ( MEMBER_LOG_NO );
ALTER TABLE SIGN_OUT_MEMBER ADD CONSTRAINT SIGN_OUT_MEMBER_PK PRIMARY KEY ( SIGN_OUT_NO );
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY ( MEMBER_NO );
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_PK PRIMARY KEY ( RESER_NO );
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( PAY_NO );
ALTER TABLE ROOM ADD CONSTRAINT ROOM_PK PRIMARY KEY ( ROOM_NO );


-- 외래키
-- 로그인(FK)&회원
ALTER TABLE MEMBER_LOG ADD CONSTRAINT MEMBER_LOG_MEMBER_FK
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) 
          ON DELETE CASCADE;


-- 회원(FK) & 예약(부모)
ALTER TABLE MEMBER
    ADD CONSTRAINT MEMBER_RESERVATION_FK FOREIGN KEY ( RESER_NO )
        REFERENCES RESERVATION ( RESER_NO );
        

--  회원(FK)&객실(부모)
ALTER TABLE MEMBER
    ADD CONSTRAINT MEMBER_ROOM_FK FOREIGN KEY ( ROOM_NO )
        REFERENCES ROOM ( ROOM_NO );

-- 회원(FK) & 결제(부모)
ALTER TABLE MEMBER
    ADD CONSTRAINT MEMBER_PAYMENT_FK FOREIGN KEY ( PAY_NO )
        REFERENCES PAYMENT ( PAY_NO );
      
        
-- 트리거 구성
-- MEMBER 테이블의 정보가 삭제되면 SIGN_OUT_MEMBER 테이블로 해당 정보가 저장되는 트리거
CREATE OR REPLACE TRIGGER SIGN_OUT_TRIGGER
    AFTER DELETE
    ON MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO SIGN_OUT_MEMBER
        (SIGN_OUT_NO, MEMBER_NO, ID, NAME, EMAIL, AGREE_STATE, SIGN_IN)
    VALUES
        (SIGN_OUT_MEMBER_SEQ.NEXTVAL, :OLD.MEMBER_NO, :OLD.ID, :OLD.NAME, :OLD.EMAIL, :OLD.AGREE_STATE, :OLD.SIGN_IN);
END SIGN_OUT_TRIGGER;        

