DROP TABLE RE_IMAGE;
DROP TABLE REVIEW_REPLY;

DROP TABLE REVIEW;
CREATE TABLE REVIEW
(
    REVIEW_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    RESER_NO  NUMBER NOT NULL,
    REVIEW_TITLE VARCHAR2(30 BYTE) NOT NULL,
    REVIEW_CONTENT VARCHAR2(200 BYTE),
    REVIEW_CREATED DATE,
    REVIEW_REV_NO NUMBER
);

DROP SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE REVIEW_SEQ NOCACHE;

CREATE TABLE REVIEW_REPLY
(
    REPLY_NO NUMBER NOT NULL,
    REVIEW_NO NUMBER NOT NULL,
    REPLY_CONTENT VARCHAR2(200 BYTE) NOT NULL,
    REPLY_CREATE DATE
);

DROP SEQUENCE REVIEW_REPLY_SEQ;
CREATE SEQUENCE REVIEW_REPLY_SEQ NOCACHE;

CREATE TABLE RE_IMAGE
(
    RE_IMAGE_NO NUMBER NOT NULL,
    REVIEW_NO NUMBER NOT NULL,
    RE_IMAGE_PATH VARCHAR2(300 BYTE),
    RE_IMAGE_SAVED VARCHAR2(40 BYTE),
    RE_IMAGE_ORIGIN VARCHAR2(300 BYTE)
);

DROP SEQUENCE RE_IMAGE_SEQ;
CREATE SEQUENCE RE_IMAGE_SEQ NOCACHE;

ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_PK PRIMARY KEY(REVIEW_NO);
ALTER TABLE REVIEW_REPLY ADD CONSTRAINT REVIEW_REPLY_PK PRIMARY KEY(REPLY_NO);
ALTER TABLE RE_IMAGE ADD CONSTRAINT RE_IMAGE_PK PRIMARY KEY(RE_IMAGE_NO);


ALTER TABLE REVIEW_REPLY 
    ADD CONSTRAINT REVIEW_REPLY_REVIEW_FK FOREIGN KEY(REVIEW_NO)
        REFERENCES REVIEW(REVIEW_NO);
        
ALTER TABLE RE_IMAGE
    ADD CONSTRAINT RE_IMAGE_REVIEW_FK FOREIGN KEY(REVIEW_NO)
        REFERENCES REVIEW(REVIEW_NO);





