DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE ROOM_TYPE;
DROP TABLE IMAGE;

CREATE TABLE RESERVATION (
	RESER_NO	NUMBER	NOT NULL,
	MEMBER_NO	NUMBER	NOT NULL,
	ROOM_NO	NUMBER	NOT NULL,
	RT_NO	NUMBER	NOT NULL,
	NON_NO	NUMBER	NOT NULL,
	RESER_CHECKIN	DATE	NULL,
	RESER_CHECKOUT	DATE	NULL,
	RESER_STATUS	NUMBER	NOT NULL,
	RESER_CNT	NUMBER	NOT NULL
);

CREATE TABLE ROOM_TYPE (
	RT_NO	NUMBER	NOT NULL,
	RT_TYPE	VARCHAR2(30 BYTE)	NOT NULL,
	RT_MAX	NUMBER	NOT NULL,
	RT_AREA	NUMBER	NOT NULL
);


CREATE TABLE ROOM (
	ROOM_NO NUMBER	NOT NULL,
	RT_NO	NUMBER	NOT NULL,
	ROOM_NAME	VARCHAR2(30 BYTE)	NOT NULL,
	ROOM_STATUS	NUMBER	NOT NULL,
	ROOM_CHECKIN	DATE	NULL,
	ROOM_CHECKOUT	DATE	NULL,
    ROOM_PRICE NUMBER NOT NULL
);



CREATE TABLE IMAGE (
	IMAGE_NO	NUMBER	NOT NULL,
	ROOM_NO	NUMBER	NOT NULL,
	IMAGE_PATH	VARCHAR2(300 BYTE)	NULL,
	IMAGE_SAVED	VARCHAR2(40 BYTE)	NULL,
	IMAGE_ORIGIN	VARCHAR2(300 BYTE)	NULL
);



ALTER TABLE RESERVATION ADD CONSTRAINT PK_RESERVATION PRIMARY KEY (
	RESER_NO
	
);

ALTER TABLE ROOM_TYPE ADD CONSTRAINT PK_ROOM_TYPE PRIMARY KEY (
	RT_NO
);



ALTER TABLE ROOM ADD CONSTRAINT PK_ROOM PRIMARY KEY (
    ROOM_NO
	
);



ALTER TABLE IMAGE ADD CONSTRAINT PK_IMAGE PRIMARY KEY (
	IMAGE_NO
	
);


ALTER TABLE RESERVATION ADD CONSTRAINT FK_ROOM_TO_RESERVATION FOREIGN KEY (
	ROOM_NO
)
REFERENCES ROOM (
	ROOM_NO
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_ROOM_TYPE_TO_RESERVATION FOREIGN KEY (
	RT_NO
)
REFERENCES ROOM_TYPE (
	RT_NO
);


ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_TYPE_TO_ROOM FOREIGN KEY (
	RT_NO
)
REFERENCES ROOM_TYPE (
	RT_NO
);

ALTER TABLE IMAGE ADD CONSTRAINT FK_ROOM_TO_IMAGE FOREIGN KEY (
	ROOM_NO
)
REFERENCES ROOM (
	ROOM_NO
);